### ISSUE TITLE
MiniCssExtractPlugin编译报错

### ISSUE THREAD

**Issue by fightingm** [dacejs/dace#2]
MiniCssExtractPlugin编译报错
![image](https://user-images.githubusercontent.com/16569801/44071092-c0327c2a-9fb9-11e8-9a71-4171b114f3df.png)

**Comment by zhongzhi107** [comment]
出于性能的考虑，在 dev 环境下默认不做 minicss 操作，如需要，请自行修改 webpack 配置文件添加。
